In [2]:
import pandas as pd

In [3]:
X = pd.read_csv("HousePrices.csv")

In [4]:
X

Id  Dwell_Type Zone_Class  LotFrontage  LotArea Road_Type Alley  \
0       1          60         RL         65.0     8450      Pave   NaN   
1       2          20         RL         80.0     9600      Pave   NaN   
2       3          60         RL         68.0    11250      Pave   NaN   
3       4          70         RL         60.0     9550      Pave   NaN   
4       5          60         RL         84.0    14260      Pave   NaN   
...   ...         ...        ...          ...      ...       ...   ...   
2068  942          60         RL          NaN     8755      Pave   NaN   
2069  943          90         RL         63.0     7711      Pave   NaN   
2070  944          90         RL        313.0    25000      Pave   NaN   
2071  945          20         RL         52.0    14375      Pave   NaN   
2072  946          50         RM         98.0     8820      Pave   NaN   

     Property_Shape LandContour Utilities  ... PoolArea PoolQC  Fence  \
0               Reg         Lvl    AllPub  ...        0    NaN    NaN   
1               Reg         Lvl    AllPub  ...        0    NaN    NaN   
2               IR1         Lvl    AllPub  ...        0    NaN    NaN   
3               IR1         Lvl    AllPub  ...        0    NaN    NaN   
4               IR1         Lvl    AllPub  ...        0    NaN    NaN   
...             ...         ...       ...  ...      ...    ...    ...   
2068            IR1         Lvl    AllPub  ...        0    NaN  GdPrv   
2069            IR1         Lvl    AllPub  ...        0    NaN    NaN   
2070            Reg         Low    AllPub  ...        0    NaN    NaN   
2071            IR1         Lvl    NoSeWa  ...        0    NaN    NaN   
2072            Reg         Lvl    AllPub  ...        0    NaN   MnWw   

     MiscFeature MiscVal MoSold YrSold  SaleType  SaleCondition  \
0            NaN       0      2   2008        WD         Normal   
1            NaN       0      5   2007        WD         Normal   
2            NaN       0      9   2008        WD         Normal   
3            NaN       0      2   2006        WD        Abnorml   
4            NaN       0     12   2008        WD         Normal   
...          ...     ...    ...    ...       ...            ...   
2068         NaN       0      6   2009        WD         Normal   
2069         NaN       0      8   2007       Oth        Abnorml   
2070         NaN       0      6   2007        WD         Normal   
2071         NaN       0      1   2009       COD        Abnorml   
2072         NaN       0      9   2009        WD         Normal   

      Property_Sale_Price  
0                  208500  
1                  181500  
2                  223500  
3                  140000  
4                  250000  
...                   ...  
2068               214000  
2069               150000  
2070               143000  
2071               137500  
2072               124900  

[2073 rows x 81 columns]

In [5]:
X.isnull().sum()

Id                       0
Dwell_Type               0
Zone_Class               0
LotFrontage            320
LotArea                  0
                      ... 
MoSold                   0
YrSold                   0
SaleType                 0
SaleCondition            0
Property_Sale_Price      0
Length: 81, dtype: int64

In [6]:
columns=X.columns[X.isnull().any()]

In [7]:
X[columns].isnull().sum()

LotFrontage      320
Alley           1944
MasVnrType        14
MasVnrArea        14
BsmtQual          59
BsmtCond          59
BsmtExposure      61
BsmtFinType1      59
BsmtFinType2      60
Electrical         1
FireplaceQu      988
GarageType       113
GarageYrBlt      113
GarageFinish     113
GarageQual       113
GarageCond       113
PoolQC          2065
Fence           1669
MiscFeature     1993
dtype: int64

In [8]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073 entries, 0 to 2072
Data columns (total 81 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Id                   2073 non-null   int64  
 1   Dwell_Type           2073 non-null   int64  
 2   Zone_Class           2073 non-null   object 
 3   LotFrontage          1753 non-null   float64
 4   LotArea              2073 non-null   int64  
 5   Road_Type            2073 non-null   object 
 6   Alley                129 non-null    object 
 7   Property_Shape       2073 non-null   object 
 8   LandContour          2073 non-null   object 
 9   Utilities            2073 non-null   object 
 10  LotConfig            2073 non-null   object 
 11  LandSlope            2073 non-null   object 
 12  Neighborhood         2073 non-null   object 
 13  Condition1           2073 non-null   object 
 14  Condition2           2073 non-null   object 
 15  Dwelling_Type        2073 non-null   o

In [9]:
X['MasVnrArea'].fillna((X['MasVnrArea'].mean()), inplace=True)

In [10]:
X['LotFrontage'].fillna((X['LotFrontage'].mean()), inplace=True)

In [11]:
X['GarageYrBlt'].fillna((X['GarageYrBlt'].mean()), inplace=True)

In [12]:
X[columns].isnull().sum()

LotFrontage        0
Alley           1944
MasVnrType        14
MasVnrArea         0
BsmtQual          59
BsmtCond          59
BsmtExposure      61
BsmtFinType1      59
BsmtFinType2      60
Electrical         1
FireplaceQu      988
GarageType       113
GarageYrBlt        0
GarageFinish     113
GarageQual       113
GarageCond       113
PoolQC          2065
Fence           1669
MiscFeature     1993
dtype: int64

In [13]:
x = X[['BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','2ndFlrSF','LowQualFinSF','GrLivArea','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd','Fireplaces','GarageYrBlt','GarageCars','MasVnrArea','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch','PoolArea','LotArea']]
y = X['Property_Sale_Price']

In [14]:
print(x,y)

      BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  2ndFlrSF  LowQualFinSF  \
0            706           0        150          856       854             0   
1            978           0        284         1262         0             0   
2            486           0        434          920       866             0   
3            216           0        540          756       756             0   
4            655           0        490         1145      1053             0   
...          ...         ...        ...          ...       ...           ...   
2068         772           0        220          992      1038             0   
2069        1440           0          0         1440         0             0   
2070           0           0       1632         1632         0             0   
2071         111         354        354          819         0             0   
2072        1088           0          0         1088       561           120   

      GrLivArea  BsmtFullBath  BsmtHalf

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model = LinearRegression()

In [17]:
model.fit(x,y)

LinearRegression()

In [18]:
model.score(x,y)

0.7747749775011854

In [19]:
model.predict([[706,0,150,856,854,0,1710,1,0,2,1,4,2,7,1,1996,2,196.0,548,0,61,0,0,0,0,8450]])

array([156799.09566957])

In [20]:
model.coef_

array([ 1.67425875e+01, -3.84966478e+00,  9.49354576e+00,  2.23864685e+01,
       -3.75288863e+00, -7.83091083e+01,  5.40749209e+01,  1.02398011e+04,
        2.59384617e+01,  1.40897910e+04,  4.65973919e+03, -1.32007420e+04,
       -4.65836723e+04,  7.15027434e+03,  6.12006579e+03,  3.54010559e+02,
        1.63158150e+04,  3.86239105e+01,  3.34106225e+00,  3.05715781e+01,
        2.10033895e+01,  1.62805184e+00,  2.86378130e+01,  6.24749855e+01,
       -2.03156463e+01,  2.32359156e-01])

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [23]:
m = LinearRegression()

In [24]:
m.fit(x_train,y_train)

LinearRegression()

# m.fit(x_train,y_train)

In [25]:
pred = m.predict(x_test)
pred

array([ 85596.38378086, 159370.73145413, 252572.63277807, 183929.94922088,
       106243.87975678, 155936.54217606,  92914.27755885, 228331.41216033,
       234106.08971354, 151112.15940139, 116867.18737731, 248016.89624569,
       335432.32538339, 180563.66522489, 239736.52833153, 267292.89756557,
       118113.50916143, 194445.19235953, 107150.69277123,  82743.74553832,
       228298.15424497, 204381.61127616, 139733.01039571, 190344.63807995,
       207305.03553102, 208166.84537689, 216215.53256404,  86152.14264631,
       231556.25233211, 155597.01429694, 279756.08769245, 214776.43396562,
       134673.00496226, 259931.09762639, 163248.72614928, 117658.22051566,
       130187.01128785, 189889.0726615 , 119201.1185561 ,  90020.75287367,
       201923.71281315, 148778.358982  , 140058.85220192,  60625.61376944,
       204673.29874413, 226827.19845874,  80946.37669832, 142524.2560497 ,
       129307.59521657, 198633.60631803,  87944.45953967, 266237.13916621,
       319071.45403231, 1

In [26]:
import numpy as np

In [27]:
from sklearn import metrics

In [28]:
test_set_r2=metrics.r2_score(y_test,pred)
print(test_set_r2)

0.7854879275160607


In [29]:
m.predict([[706,0,150,856,854,0,1710,1,0,2,1,4,2,7,1,1996,2,196.0,548,0,61,0,0,0,0,8450]])

array([155699.79614132])